"""add interview date

Revision ID: ba7d8c95adf9
Revises: 3de33d1407aa
Create Date: 2026-03-30 19:23:31.206830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7d8c95adf9'
down_revision = '3de33d1407aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable='False')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable='False')
        batch_op.alter_column('cgpa',
               existing_type=sa.FLOAT(),
               nullable='False')
        batch_op.alter_column('graduation_year',
               existing_type=sa.INTEGER(),
               nullable='False')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('graduation_year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cgpa',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('interview_date')

    # ### end Alembic commands ###
